# Generated by Django 6.0.5 on 2026-05-20 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagada', 'Pagada'), ('preparando', 'En preparación'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('metodo_de_pago', models.CharField(blank=True, choices=[('stripe', 'Tarjeta de crédito/débito'), ('mercadopago', 'MercadoPago')], max_length=20)),
                ('total_en_gs', models.IntegerField()),
                ('direccion_de_envio', models.TextField()),
                ('ciudad_de_envio', models.CharField(max_length=100)),
                ('telefono_de_envio', models.CharField(max_length=20)),
                ('id_pago_externo', models.CharField(blank=True, max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_del_comprador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'ordenes',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemDeOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario_en_gs', models.IntegerField()),
                ('subtotal_en_gs', models.IntegerField()),
                ('variante_comprada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veces_que_fue_comprada', to='products.variante')),
                ('orden_a_la_que_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_de_la_orden', to='orders.orden')),
            ],
            options={
                'db_table': 'items_de_orden',
            },
        ),
    ]
