# Generated by Django 6.0.5 on 2026-05-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='metodo_de_pago',
            field=models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Pago en efectivo')], max_length=20),
        ),
    ]
