# Generated by Django 6.0.5 on 2026-05-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_utilizado', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Pago en efectivo')], max_length=20)),
                ('monto_cobrado_gs', models.IntegerField()),
                ('estado_del_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('codigo_de_pago', models.CharField(blank=True, max_length=100)),
                ('ultimos_4_digitos', models.CharField(blank=True, max_length=4)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('observacion_del_admin', models.TextField(blank=True)),
                ('fecha_del_pago', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden_pagada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago_de_la_orden', to='orders.orden')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_del_pago'],
            },
        ),
    ]
