# Generated by Django 6.0.5 on 2026-05-20 23:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('titulo_de_la_resena', models.CharField(max_length=200)),
                ('cuerpo_de_la_resena', models.TextField()),
                ('estado_de_moderacion', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('escrita_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('autor_de_la_resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_escritas_por_el_usuario', to=settings.AUTH_USER_MODEL)),
                ('producto_reseñado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_del_producto', to='products.producto')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'db_table': 'resenas',
                'ordering': ['-escrita_en'],
                'unique_together': {('producto_reseñado', 'autor_de_la_resena')},
            },
        ),
    ]
