# Generated by Django 6.0.5 on 2026-06-10 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resena',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='resena',
            table=None,
        ),
    ]
